
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class Libsym {
  /* terminals */
  public static final int CLASS = 15;
  public static final int INT = 3;
  public static final int LP = 7;
  public static final int RP = 8;
  public static final int CLASSIDENT = 16;
  public static final int LIBRARY = 17;
  public static final int ID = 18;
  public static final int STATIC = 2;
  public static final int STRING_LITERAL = 19;
  public static final int LB = 9;
  public static final int BOOLEAN = 4;
  public static final int RB = 10;
  public static final int STRING = 5;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int LSQUARE = 11;
  public static final int error = 1;
  public static final int RSQUARE = 12;
  public static final int SEMI_COL = 14;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STATIC",
  "INT",
  "BOOLEAN",
  "STRING",
  "VOID",
  "LP",
  "RP",
  "LB",
  "RB",
  "LSQUARE",
  "RSQUARE",
  "COMMA",
  "SEMI_COL",
  "CLASS",
  "CLASSIDENT",
  "LIBRARY",
  "ID",
  "STRING_LITERAL"
  };
}

