
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int CLASSIDENT = 47;
  public static final int STRING_LITERAL = 49;
  public static final int SEMI_COL = 43;
  public static final int UMINUS = 45;
  public static final int NOTEQUAL = 26;
  public static final int GREATER = 31;
  public static final int CONTINUE = 14;
  public static final int INT = 6;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int STATIC = 4;
  public static final int NOT = 27;
  public static final int AND = 33;
  public static final int LESSEQUAL = 28;
  public static final int LP = 35;
  public static final int OR = 34;
  public static final int COMMA = 42;
  public static final int CLASS = 2;
  public static final int RP = 36;
  public static final int PLUS = 22;
  public static final int ASSIGN = 44;
  public static final int IF = 10;
  public static final int THIS = 15;
  public static final int ID = 48;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int LB = 37;
  public static final int RETURN = 9;
  public static final int EQUAL = 32;
  public static final int TRUE = 18;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int RB = 38;
  public static final int NULL = 20;
  public static final int NUMBER = 46;
  public static final int MOD = 25;
  public static final int BREAK = 13;
  public static final int VOID = 5;
  public static final int GREATEREQUAL = 30;
  public static final int TIMES = 23;
  public static final int ELSE = 11;
  public static final int LSQUARE = 39;
  public static final int RSQUARE = 40;
  public static final int WHILE = 12;
  public static final int EXTENDS = 3;
  public static final int STRING = 8;
  public static final int FALSE = 19;
  public static final int LENGTH = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "STRING",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NULL",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "NOTEQUAL",
  "NOT",
  "LESSEQUAL",
  "LESS",
  "GREATEREQUAL",
  "GREATER",
  "EQUAL",
  "AND",
  "OR",
  "LP",
  "RP",
  "LB",
  "RB",
  "LSQUARE",
  "RSQUARE",
  "DOT",
  "COMMA",
  "SEMI_COL",
  "ASSIGN",
  "UMINUS",
  "NUMBER",
  "CLASSIDENT",
  "ID",
  "STRING_LITERAL"
  };
}

